name: flutter_pudong
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  auto_route: ^0.5.0
  cached_network_image: ^2.2.0+1
  cookie_jar: ^1.0.1
  date_format: ^1.0.8
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  extended_image: ^0.7.3+1
  event_bus: ^1.1.1
  fluro: ^1.6.3
  flutter_easyrefresh: ^2.1.1
  flutter_spinkit: ^4.1.2+1
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.11
  flutter_xupdate: ^0.0.3
  image_picker_saver: ^0.3.0
  oktoast: ^2.3.2
  path_provider: ^1.6.8
  package_info: ^0.4.0+18
  permission_handler: ^5.0.0+hotfix.5
  provider: ^4.1.1
  shared_preferences: ^0.5.7+2
  share: ^0.6.4+2
  url_launcher: ^5.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.5.0  

flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/
    
  fonts:
    - family: xuifont  #指定一个字体名
      fonts:
        - asset: assets/fonts/iconfont.ttf
